require: rubocop-rails

AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - .git/**/*
    - bin/**/*
    - db/schema.rb
    - app/controllers/invitations_controller.rb
    - app/controllers/users/*

Style/Documentation:
  Enabled: false
