require: rubocop-rails

AllCops:
  Exclude:
    - node_modules/**/*
    - vendor/**/*
    - .git/**/*
    - bin/**/*
    - db/schema.rb
    - app/controllers/invitations_controller.rb
    - app/controllers/users/*
    - config/routes.rb
    - config/initializers/devise.rb
    - config/environments/development.rb

Style/Documentation:
  Enabled: false
